NUMBER_OF_SIDE_CELLS = 10
NUMBER_OF_MINES = 10

CELL_SIZE = 32
GRID_WIDTH = 1
# Total length of cells + total length of grid
SCREEN_SIZE = CELL_SIZE * NUMBER_OF_SIDE_CELLS + \
    (NUMBER_OF_SIDE_CELLS * GRID_WIDTH + GRID_WIDTH)

GRID_COLOR = 'grey'
